version: 2
accept_configuration:
  condition: property
  property: features
  not_contains_value: Disable

instructions:
  Build:
    - type: AppendToEnvironmentVariable
      variableName: COMMON_NON_QTBASE_CMAKE_ARGS
      variableValue: " -DQT_INTERNAL_FORCE_NO_GENERATE_SBOM=ON"
    - type: AppendToEnvironmentVariable
      variableName: COMMON_NON_QTBASE_TARGET_CMAKE_ARGS
      variableValue: " -DQT_INTERNAL_FORCE_NO_GENERATE_SBOM=ON"
    - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"

  Test: []
